config/routes.rb
Rails.application.routes.draw do

  #getting resouces-->

  devise_for :users
  resources :songs
  resources :albums
  resources :artists

  #setting routes

  get 'main/contact'
  get 'main/index'

  #setting root view

  root 'main#index'
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :song
    has_many :song
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:alb_id, :alb_name, :alb_year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:art_id, :art_name)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def musics
  end

  def contact
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:sid, :name, :link, :favourite)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--placeholder for preview of the input slot-->

  <div class="field form-group">
    <br>
    <%= form.label :Album_ID %>
    <%= form.text_field :alb_id, class:"form-control", placeholder:"Album ID" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :Album_Name %>
    <%= form.text_field :alb_name, class:"form-control", placeholder:"Album Name"  %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :Release_year %>
    <%= form.text_field :alb_year, class:"form-control" , placeholder:"Release Year" %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<!--
  LOGIC:
  for signed in user and is an admin,
  they can edit and destroy items, appliable to other views.
  Otherwise for visitors and non admin users visiting edit page there will be an alert message for them.
-->

<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <h1>Editing Album</h1>

    <%= render 'form', album: @album %>
    <br>
    <%= link_to 'Show', @album, class:"btn btn-outline-secondary"%>
    <%= link_to 'Back', albums_path, class:"btn btn-outline-secondary" %>

      <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

          <h1><br>🚫Hey looks like you're not authorized yet, click <%= link_to "here", :back %> to go back🚫</h1>
      <% end %>

<% end %>

app/views/albums/index.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<h1>Albums</h1>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Album Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.alb_name %></td>

                <!--
                  LOGIC:
                  for signed in user and is an admin,
                  they can edit and destroy items, appliable to other views.
                  Otherwise for visitors and non admin users can only see show button.
                -->

        <% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>

          <td><%= link_to "Show", album %></td>
          <td><%= link_to 'Edit', edit_album_path(album) %></td>
          <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

          <td><%= link_to 'Show', album %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <%= link_to 'New Album', new_album_path, class:"btn btn-outline-secondary" %>
<% end %>
<br><br>
<%= link_to "Back", songs_path, class:"btn btn-outline-secondary"%>
<br>

app/views/albums/new.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>
<h1>New Album</h1>

<%= render 'form', album: @album, class:"btn btn-outline-secondary" %>
<br>
<%= link_to 'Back', albums_path, class:"btn btn-outline-secondary"  %>
<br>

app/views/albums/show.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<div class="jumbotron">
  <h1 class="display-4"><%= @album.alb_name %></h1>
  <p class="lead">Release year: <%= @album.alb_year %></p>
  <hr class="my-4">
  <p>Album ID: <%= @album.alb_id %></p>
</div>

<body bgcolor= "#242424">

</body>

<% link_to 'Edit', edit_album_path(@album) , class:"btn btn-outline-secondary"%>
<%= link_to 'Back', albums_path, class:"btn btn-outline-secondary" %>

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <br>
    <%= form.label :artist_ID %>
    <%= form.text_field :art_id, class:"form-control", placeholder:"Artist ID" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :Artist_Name %>
    <%= form.text_field :art_name, class:"form-control", placeholder:"Artist Name" %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<!--
  LOGIC:
  for signed in user and is an admin,
  they can edit and destroy items, appliable to other views.
  Otherwise for visitors and non admin users visiting edit page there will be an alert message for them.
-->

<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

  <%= link_to 'Show', @artist, class:"btn btn-outline-secondary" %>
  <%= link_to 'Back', artists_path, class:"btn btn-outline-secondary" %>

  <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

      <h1><br>🚫Hey looks like you're not authorized yet, click <%= link_to "here", :back %> to go back🚫</h1>
  <% end %>

  <% end %>

app/views/artists/index.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<h1>Artists</h1>

  <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Artist Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>

        <td><%= artist.art_name %></td>

                <!--
                  LOGIC:
                  for signed in user and is an admin,
                  they can edit and destroy items, appliable to other views.
                  Otherwise for visitors and non admin users can only see show button.
                -->


        <% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>

          <td><%= link_to 'Show', artist %></td>
          <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
          <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

            <td><%= link_to 'Show', artist %></td>
            <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <%= link_to 'New Artist', new_artist_path, class:"btn btn-outline-secondary"%>
<% end %>
<br><br>
<%= link_to "Back", songs_path, class:"btn btn-outline-secondary" %>
<br>

app/views/artists/new.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>
<br>
<%= link_to 'Back', artists_path, class:"btn btn-outline-secondary" %>
<br>

app/views/artists/show.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<div class="jumbotron">
  <h1 class="display-4"><%= @artist.art_name %></h1>

  <hr class="my-4">
  <p>Artist ID: <%= @artist.art_id %></p>
</div>

<% link_to 'Edit', edit_artist_path(@artist) %>
<%= link_to 'Back', artists_path , class:"btn btn-outline-secondary"%>

app/views/layouts/_alert.html.erb
<div class="alert alert-dark alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>My music collection</title>
  </head>
  <body>
    <%= render 'main/home' %>
    <div class='container'>
      <br>
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>

    <br>
      <%= yield %>
    <br>
    </div>

  </body>
</html>

app/views/main/_home.html.erb
<nav class="navbar navbar-light bg-light", style:'font-color= #000000;'>
  <div class="container-fluid">

    <strong><%= link_to 'Home', root_path, class:"navbar-brand"%></strong>

    <%= link_to 'Contact Us', main_contact_path, class:"nav-link" %>

    <% if user_signed_in? %>
      <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
    <% else %>

      <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
      <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>

    <% end %>
  </div>
</nav>

app/views/main/contact.html.erb
<h1>Contact Me</h1>
<p>Got any problem? Email me for the issue.<br></p>
<p>Email: <a href="mailto:hl01341@surrey.ac.uk">hl01341@surrey.ac.uk</a><br>Name: HoYu Lee</p>
<br><br>
<%= link_to "Back", :back , class:"btn btn-outline-secondary"%>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">

    <meta charset="utf-8">
    <title>My music collection</title>
  </head>
  <body>
    <% if user_signed_in? %>
      <p>Hi <%= current_user.email %></p>
      <h1>Welcome to Terry's music collection!</h1><br>
      <p>Hello welcome to my music collection. In here you will see some of the songs from my library and few of my favourite songs among all. Some of the most famous artist around the world are here as well!<br><br>Enjoy!</p>
    <% else %>
      <h1>Welcome to Terry's music collection!</h1><br>
      <p>Hello welcome to my music collection. In here you will see some of the songs from my library and few of my favourite songs among all. Some of the most famous artist around the world are here as well!<br><br>Enjoy!</p><p style="color: yellow;">If you are an admin, you can log in with email: "admin@gmail.com" and password: "123456"</p>
    <% end %>
    <br>
    <%= link_to "My music collection", songs_path, class:"btn btn-outline-secondary" %>
    <br>

    <div class="box">
    </div>

    <div style="width: 980px; margin: 0 auto; overflow: hidden;">
    </div>


  </body>




</html>

app/views/songs/_form.html.erb
<%= form_with(model: song, local: true) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :Song_ID %>
    <%= form.text_field :sid, class:"form-control", placeholder:"Song ID"  %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :Song_Name %>
    <%= form.text_field :name , class:"form-control", placeholder:"Song Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :Song_Link %>
    <%= form.text_field :link, class:"form-control", placeholder:"Song Link"  %>
  </div>

  <br>

  <div class="field">
    <%= form.label :My_favourite %>
    <%= form.check_box :favourite %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/songs/edit.html.erb
<!--
  LOGIC:
  for signed in user and is an admin,
  they can edit and destroy items, appliable to other views.
  Otherwise for visitors and non admin users visiting edit page there will be an alert message for them.
-->

<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <h1>Editing Song</h1>

  <%= render 'form', song: @song %>

    <%= link_to 'Show', @song, class:"btn btn-outline-secondary"%>
    <%= link_to 'Back', songs_path, class:"btn btn-outline-secondary"%>

    <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

        <h1><br>🚫Hey looks like you're not authorized yet, click <%= link_to "here", :back %> to go back🚫</h1>
    <% end %>

<% end %>

app/views/songs/index.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<h1>Songs</h1>
<br>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th>Song Name</th>
      <th>Favourite?</th>
      <th colspan="4"></th>
    </tr>
  </thead>


  <tbody>
    <% @songs.each do |song| %>
      <tr>

        <td><%= song.name %></td>

        <td>
          <% if song.favourite == true %>                  <!--For true result returns Yes, false returns No-->
            Yes
          <% else %>
            No
          <% end %>
        </td>

        <!--
          LOGIC:
          for signed in user and is an admin,
          they can edit and destroy items, appliable to other views.
          Otherwise for visitors and non admin users can only see show button.
        -->

        <% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>

            <td><%= link_to 'Show', song %></td>
            <td><%= link_to 'Edit', edit_song_path(song) %></td>
            <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          <% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>

            <td><%= link_to 'Show', song %></td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<!--

All visitors not allowed to add songs to my collection except using admin account

-->

<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
  <%= link_to 'New songs', new_song_path , class:"btn btn-outline-secondary"%>
<% end %>
<br><br>
<%= link_to 'Albums', albums_path , class:"btn btn-outline-secondary"%>
<%= link_to 'Artists', artists_path , class:"btn btn-outline-secondary"%>
<br>

app/views/songs/new.html.erb
<h1>New Song</h1>

<br>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path, class:"btn btn-outline-secondary"%>

app/views/songs/show.html.erb
<head>
  <link rel="icon" href="https://cdn.icon-icons.com/icons2/38/PNG/512/music_5261.png">
</head>

<div class="jumbotron">
  <h1 class="display-4"><%= @song.name %></h1>
  <p class="lead">Link to song: <%= link_to @song.link , "#{@song.link}" , target: :_blank %></p>
  <hr class="my-4">
  <p>Song ID: <%= @song.sid %></p>
</div>

<p>
  <strong>Favourite?...</strong>
  <% if @song.favourite == true %>
    Yes!
  <% else %>
    No
  <% end %>
</p>

<% if user_signed_in? == true && current_user.email == "admin@gmail.com" %>
<%= link_to 'Edit', edit_song_path(@song) , class:"btn btn-outline-secondary"%>
<% else if user_signed_in? == false || current_user.email != "admin@gmail.com" %>
<%= link_to 'Back', songs_path, class:"btn btn-outline-secondary" %>
<% end %>
<% end %>